<a href="https://colab.research.google.com/github/Gwynbl31dd/ML_Test/blob/master/Array_vs_lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays vs lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [7]:
for e in L:
  print(e)

1
2
3
4


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [8]:
# broadcasting
A + np.array([4])

array([5, 6, 7])

In [9]:
# Does a regular vector addition
A + np.array([4,5,6])

array([5, 7, 9])

In [10]:
2 * A

array([2, 4, 6])

In [11]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [13]:
L2 = []
for e in L:
  L2.append(e + 3)

In [14]:
L2

[4, 5, 6, 7]

In [15]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [17]:
L2 = []
for e in L:
  L2.append(e**2)
L2

[1, 4, 9, 16]

In [18]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [19]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [20]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [21]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])