<a href="https://colab.research.google.com/github/Gwynbl31dd/ML_Test/blob/master/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices

In [6]:
import numpy as np

In [1]:
L = [[1,2],[3,4]]

In [2]:
L[0]

[1, 2]

In [3]:
L[0][1]

2

In [8]:
A = np.array(L)

In [9]:
A[0][1]

2

In [10]:
A[0,1]

2

In [11]:
A[:,0]

array([1, 3])

In [12]:
A.T

array([[1, 3],
       [2, 4]])

In [13]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [16]:
B = np.array([[1,2,3],[4,5,6]])

In [17]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [18]:
np.linalg.det(A)

-2.0000000000000004

In [19]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
np.trace(A)

5

In [21]:
np.diag(A)

array([1, 4])

In [22]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [24]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [25]:
Lam, V = np.linalg.eig(A)

In [26]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [27]:
np.allclose(V[:,0] * Lam[0],A @ V[:,0])

True